export const DATA = [
 {
   "ident": "KABQ",
   "type": "large_airport",
   "name": "Albuquerque International Sunport Airport",
   "coordinates": "35.04019928, -106.6090012",
   "elevation_ft": 5355,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NM",
   "municipality": "Albuquerque",
   "gps_code": "KABQ",
   "iata_code": "ABQ",
   "local_code": "ABQ"
 },
 {
   "ident": "KADW",
   "type": "large_airport",
   "name": "Andrews Air Force Base",
   "coordinates": "38.81079865, -76.86699677",
   "elevation_ft": 280,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MD",
   "municipality": "Camp Springs",
   "gps_code": "KADW",
   "iata_code": "ADW",
   "local_code": "ADW"
 },
 {
   "ident": "KAFW",
   "type": "large_airport",
   "name": "Fort Worth Alliance Airport",
   "coordinates": "32.98759842, -97.31880188",
   "elevation_ft": 722,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Fort Worth",
   "gps_code": "KAFW",
   "iata_code": "AFW",
   "local_code": "AFW"
 },
 {
   "ident": "KAGS",
   "type": "large_airport",
   "name": "Augusta Regional At Bush Field",
   "coordinates": "33.36989975, -81.96450043",
   "elevation_ft": 144,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-GA",
   "municipality": "Augusta",
   "gps_code": "KAGS",
   "iata_code": "AGS",
   "local_code": "AGS"
 },
 {
   "ident": "KAMA",
   "type": "large_airport",
   "name": "Rick Husband Amarillo International Airport",
   "coordinates": "35.2193985, -101.7060013",
   "elevation_ft": 3607,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Amarillo",
   "gps_code": "KAMA",
   "iata_code": "AMA",
   "local_code": "AMA"
 },
 {
   "ident": "KATL",
   "type": "large_airport",
   "name": "Hartsfield Jackson Atlanta International Airport",
   "coordinates": "33.63669968, -84.42810059",
   "elevation_ft": 1026,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-GA",
   "municipality": "Atlanta",
   "gps_code": "KATL",
   "iata_code": "ATL",
   "local_code": "ATL"
 },
 {
   "ident": "KAUS",
   "type": "large_airport",
   "name": "Austin Bergstrom International Airport",
   "coordinates": "30.19449997, -97.66989899",
   "elevation_ft": 542,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Austin",
   "gps_code": "KAUS",
   "iata_code": "AUS",
   "local_code": "AUS"
 },
 {
   "ident": "KAVL",
   "type": "large_airport",
   "name": "Asheville Regional Airport",
   "coordinates": "35.43619919, -82.54180145",
   "elevation_ft": 2165,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NC",
   "municipality": "Asheville",
   "gps_code": "KAVL",
   "iata_code": "AVL",
   "local_code": "AVL"
 },
 {
   "ident": "KBAB",
   "type": "large_airport",
   "name": "Beale Air Force Base",
   "coordinates": "39.13610077, -121.4369965",
   "elevation_ft": 113,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Marysville",
   "gps_code": "KBAB",
   "iata_code": "BAB",
   "local_code": "BAB"
 },
 {
   "ident": "KBAD",
   "type": "large_airport",
   "name": "Barksdale Air Force Base",
   "coordinates": "32.50180054, -93.66269684",
   "elevation_ft": 166,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-LA",
   "municipality": "Bossier City",
   "gps_code": "KBAD",
   "iata_code": "BAD",
   "local_code": "BAD"
 },
 {
   "ident": "KBDL",
   "type": "large_airport",
   "name": "Bradley International Airport",
   "coordinates": "41.93889999, -72.68319702",
   "elevation_ft": 173,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CT",
   "municipality": "Hartford",
   "gps_code": "KBDL",
   "iata_code": "BDL",
   "local_code": "BDL"
 },
 {
   "ident": "KBFI",
   "type": "large_airport",
   "name": "Boeing Field King County International Airport",
   "coordinates": "47.52999878, -122.302002",
   "elevation_ft": 21,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WA",
   "municipality": "Seattle",
   "gps_code": "KBFI",
   "iata_code": "BFI",
   "local_code": "BFI"
 },
 {
   "ident": "KBGR",
   "type": "large_airport",
   "name": "Bangor International Airport",
   "coordinates": "44.80739975, -68.82810211",
   "elevation_ft": 192,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-ME",
   "municipality": "Bangor",
   "gps_code": "KBGR",
   "iata_code": "BGR",
   "local_code": "BGR"
 },
 {
   "ident": "KBHM",
   "type": "large_airport",
   "name": "Birmingham-Shuttlesworth International Airport",
   "coordinates": "33.56290054, -86.75350189",
   "elevation_ft": 650,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AL",
   "municipality": "Birmingham",
   "gps_code": "KBHM",
   "iata_code": "BHM",
   "local_code": "BHM"
 },
 {
   "ident": "KBIL",
   "type": "large_airport",
   "name": "Billings Logan International Airport",
   "coordinates": "45.80770111, -108.5429993",
   "elevation_ft": 3652,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MT",
   "municipality": "Billings",
   "gps_code": "KBIL",
   "iata_code": "BIL",
   "local_code": "BIL"
 },
 {
   "ident": "KBLV",
   "type": "large_airport",
   "name": "Scott AFB/Midamerica Airport",
   "coordinates": "38.54520035, -89.83519745",
   "elevation_ft": 459,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Belleville",
   "gps_code": "KBLV",
   "iata_code": "BLV",
   "local_code": "BLV"
 },
 {
   "ident": "KBMI",
   "type": "large_airport",
   "name": "Central Illinois Regional Airport at Bloomington-Normal",
   "coordinates": "40.47710037, -88.91590118",
   "elevation_ft": 871,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Bloomington/Normal",
   "gps_code": "KBMI",
   "iata_code": "BMI",
   "local_code": "BMI"
 },
 {
   "ident": "KBNA",
   "type": "large_airport",
   "name": "Nashville International Airport",
   "coordinates": "36.12450027, -86.67819977",
   "elevation_ft": 599,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TN",
   "municipality": "Nashville",
   "gps_code": "KBNA",
   "iata_code": "BNA",
   "local_code": "BNA"
 },
 {
   "ident": "KBOI",
   "type": "large_airport",
   "name": "Boise Air Terminal/Gowen field",
   "coordinates": "43.56439972, -116.2229996",
   "elevation_ft": 2871,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-ID",
   "municipality": "Boise",
   "gps_code": "KBOI",
   "iata_code": "BOI",
   "local_code": "BOI"
 },
 {
   "ident": "KBOS",
   "type": "large_airport",
   "name": "General Edward Lawrence Logan International Airport",
   "coordinates": "42.36429977, -71.00520325",
   "elevation_ft": 20,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MA",
   "municipality": "Boston",
   "gps_code": "KBOS",
   "iata_code": "BOS",
   "local_code": "BOS"
 },
 {
   "ident": "KBTR",
   "type": "large_airport",
   "name": "Baton Rouge Metropolitan, Ryan Field",
   "coordinates": "30.53319931, -91.14959717",
   "elevation_ft": 70,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-LA",
   "municipality": "Baton Rouge",
   "gps_code": "KBTR",
   "iata_code": "BTR",
   "local_code": "BTR"
 },
 {
   "ident": "KBUF",
   "type": "large_airport",
   "name": "Buffalo Niagara International Airport",
   "coordinates": "42.94049835, -78.73220062",
   "elevation_ft": 728,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NY",
   "municipality": "Buffalo",
   "gps_code": "KBUF",
   "iata_code": "BUF",
   "local_code": "BUF"
 },
 {
   "ident": "KBWI",
   "type": "large_airport",
   "name": "Baltimore/Washington International Thurgood Marshall Airport",
   "coordinates": "39.17539978, -76.66829681",
   "elevation_ft": 146,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MD",
   "municipality": "Baltimore",
   "gps_code": "KBWI",
   "iata_code": "BWI",
   "local_code": "BWI"
 },
 {
   "ident": "KCAE",
   "type": "large_airport",
   "name": "Columbia Metropolitan Airport",
   "coordinates": "33.93880081, -81.11949921",
   "elevation_ft": 236,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-SC",
   "municipality": "Columbia",
   "gps_code": "KCAE",
   "iata_code": "CAE",
   "local_code": "CAE"
 },
 {
   "ident": "KCBM",
   "type": "large_airport",
   "name": "Columbus Air Force Base",
   "coordinates": "33.64379883, -88.44380188",
   "elevation_ft": 219,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MS",
   "municipality": "Columbus",
   "gps_code": "KCBM",
   "iata_code": "CBM",
   "local_code": "CBM"
 },
 {
   "ident": "KCHA",
   "type": "large_airport",
   "name": "Lovell Field",
   "coordinates": "35.03530121, -85.20379639",
   "elevation_ft": 683,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TN",
   "municipality": "Chattanooga",
   "gps_code": "KCHA",
   "iata_code": "CHA",
   "local_code": "CHA"
 },
 {
   "ident": "KCHS",
   "type": "large_airport",
   "name": "Charleston Air Force Base-International Airport",
   "coordinates": "32.89860153, -80.04049683",
   "elevation_ft": 46,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-SC",
   "municipality": "Charleston",
   "gps_code": "KCHS",
   "iata_code": "CHS",
   "local_code": "CHS"
 },
 {
   "ident": "KCID",
   "type": "large_airport",
   "name": "The Eastern Iowa Airport",
   "coordinates": "41.88470078, -91.71080017",
   "elevation_ft": 869,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IA",
   "municipality": "Cedar Rapids",
   "gps_code": "KCID",
   "iata_code": "CID",
   "local_code": "CID"
 },
 {
   "ident": "KCLE",
   "type": "large_airport",
   "name": "Cleveland Hopkins International Airport",
   "coordinates": "41.4117012, -81.84980011",
   "elevation_ft": 791,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OH",
   "municipality": "Cleveland",
   "gps_code": "KCLE",
   "iata_code": "CLE",
   "local_code": "CLE"
 },
 {
   "ident": "KCLT",
   "type": "large_airport",
   "name": "Charlotte Douglas International Airport",
   "coordinates": "35.2140007, -80.94309998",
   "elevation_ft": 748,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NC",
   "municipality": "Charlotte",
   "gps_code": "KCLT",
   "iata_code": "CLT",
   "local_code": "CLT"
 },
 {
   "ident": "KCMH",
   "type": "large_airport",
   "name": "Port Columbus International Airport",
   "coordinates": "39.9980011, -82.89189911",
   "elevation_ft": 815,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OH",
   "municipality": "Columbus",
   "gps_code": "KCMH",
   "iata_code": "CMH",
   "local_code": "CMH"
 },
 {
   "ident": "KCOS",
   "type": "large_airport",
   "name": "City of Colorado Springs Municipal Airport",
   "coordinates": "38.80580139, -104.7009964",
   "elevation_ft": 6187,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CO",
   "municipality": "Colorado Springs",
   "gps_code": "KCOS",
   "iata_code": "COS",
   "local_code": "COS"
 },
 {
   "ident": "KCPR",
   "type": "large_airport",
   "name": "Casper-Natrona County International Airport",
   "coordinates": "42.90800095, -106.4639969",
   "elevation_ft": 5350,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WY",
   "municipality": "Casper",
   "gps_code": "KCPR",
   "iata_code": "CPR",
   "local_code": "CPR"
 },
 {
   "ident": "KCRP",
   "type": "large_airport",
   "name": "Corpus Christi International Airport",
   "coordinates": "27.77039909, -97.50119781",
   "elevation_ft": 44,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Corpus Christi",
   "gps_code": "KCRP",
   "iata_code": "CRP",
   "local_code": "CRP"
 },
 {
   "ident": "KCRW",
   "type": "large_airport",
   "name": "Yeager Airport",
   "coordinates": "38.37310028, -81.59320068",
   "elevation_ft": 981,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WV",
   "municipality": "Charleston",
   "gps_code": "KCRW",
   "iata_code": "CRW",
   "local_code": "CRW"
 },
 {
   "ident": "KCVG",
   "type": "large_airport",
   "name": "Cincinnati Northern Kentucky International Airport",
   "coordinates": "39.04880142, -84.6678009",
   "elevation_ft": 896,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-KY",
   "municipality": "Cincinnati",
   "gps_code": "KCVG",
   "iata_code": "CVG",
   "local_code": "CVG"
 },
 {
   "ident": "KCVS",
   "type": "large_airport",
   "name": "Cannon Air Force Base",
   "coordinates": "34.38280106, -103.3219986",
   "elevation_ft": 4295,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NM",
   "municipality": "Clovis",
   "gps_code": "KCVS",
   "iata_code": "CVS",
   "local_code": "CVS"
 },
 {
   "ident": "KDAL",
   "type": "large_airport",
   "name": "Dallas Love Field",
   "coordinates": "32.8470993, -96.85179901",
   "elevation_ft": 487,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Dallas",
   "gps_code": "KDAL",
   "iata_code": "DAL",
   "local_code": "DAL"
 },
 {
   "ident": "KDAY",
   "type": "large_airport",
   "name": "James M Cox Dayton International Airport",
   "coordinates": "39.90240097, -84.2193985",
   "elevation_ft": 1009,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OH",
   "municipality": "Dayton",
   "gps_code": "KDAY",
   "iata_code": "DAY",
   "local_code": "DAY"
 },
 {
   "ident": "KDBQ",
   "type": "large_airport",
   "name": "Dubuque Regional Airport",
   "coordinates": "42.40200043, -90.70950317",
   "elevation_ft": 1077,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IA",
   "municipality": "Dubuque",
   "gps_code": "KDBQ",
   "iata_code": "DBQ",
   "local_code": "DBQ"
 },
 {
   "ident": "KDCA",
   "type": "large_airport",
   "name": "Ronald Reagan Washington National Airport",
   "coordinates": "38.85210037, -77.03769684",
   "elevation_ft": 15,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-DC",
   "municipality": "Washington",
   "gps_code": "KDCA",
   "iata_code": "DCA",
   "local_code": "DCA"
 },
 {
   "ident": "KDEN",
   "type": "large_airport",
   "name": "Denver International Airport",
   "coordinates": "39.86169815, -104.6729965",
   "elevation_ft": 5431,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CO",
   "municipality": "Denver",
   "gps_code": "KDEN",
   "iata_code": "DEN",
   "local_code": "DEN"
 },
 {
   "ident": "KDFW",
   "type": "large_airport",
   "name": "Dallas Fort Worth International Airport",
   "coordinates": "32.89680099, -97.03800201",
   "elevation_ft": 607,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Dallas-Fort Worth",
   "gps_code": "KDFW",
   "iata_code": "DFW",
   "local_code": "DFW"
 },
 {
   "ident": "KDLF",
   "type": "large_airport",
   "name": "Laughlin Air Force Base",
   "coordinates": "29.35950089, -100.7779999",
   "elevation_ft": 1082,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Del Rio",
   "gps_code": "KDLF",
   "iata_code": "DLF",
   "local_code": "DLF"
 },
 {
   "ident": "KDLH",
   "type": "large_airport",
   "name": "Duluth International Airport",
   "coordinates": "46.84209824, -92.19360352",
   "elevation_ft": 1428,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MN",
   "municipality": "Duluth",
   "gps_code": "KDLH",
   "iata_code": "DLH",
   "local_code": "DLH"
 },
 {
   "ident": "KDOV",
   "type": "large_airport",
   "name": "Dover Air Force Base",
   "coordinates": "39.12950134, -75.46600342",
   "elevation_ft": 24,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-DE",
   "municipality": "Dover",
   "gps_code": "KDOV",
   "iata_code": "DOV",
   "local_code": "DOV"
 },
 {
   "ident": "KDSM",
   "type": "large_airport",
   "name": "Des Moines International Airport",
   "coordinates": "41.5340004, -93.6631012",
   "elevation_ft": 958,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IA",
   "municipality": "Des Moines",
   "gps_code": "KDSM",
   "iata_code": "DSM",
   "local_code": "DSM"
 },
 {
   "ident": "KDTW",
   "type": "large_airport",
   "name": "Detroit Metropolitan Wayne County Airport",
   "coordinates": "42.21239853, -83.35340118",
   "elevation_ft": 645,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MI",
   "municipality": "Detroit",
   "gps_code": "KDTW",
   "iata_code": "DTW",
   "local_code": "DTW"
 },
 {
   "ident": "KDYS",
   "type": "large_airport",
   "name": "Dyess Air Force Base",
   "coordinates": "32.42079926, -99.854599",
   "elevation_ft": 1789,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Abilene",
   "gps_code": "KDYS",
   "iata_code": "DYS",
   "local_code": "DYS"
 },
 {
   "ident": "KEDW",
   "type": "large_airport",
   "name": "Edwards Air Force Base",
   "coordinates": "34.90539932, -117.8840027",
   "elevation_ft": 2312,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Edwards",
   "gps_code": "KEDW",
   "iata_code": "",
   "local_code": "EDW"
 },
 {
   "ident": "KEND",
   "type": "large_airport",
   "name": "Vance Air Force Base",
   "coordinates": "36.33919907, -97.91649628",
   "elevation_ft": 1307,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OK",
   "municipality": "Enid",
   "gps_code": "KEND",
   "iata_code": "END",
   "local_code": "END"
 },
 {
   "ident": "KERI",
   "type": "large_airport",
   "name": "Erie International Tom Ridge Field",
   "coordinates": "42.08312701, -80.17386675",
   "elevation_ft": 732,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-PA",
   "municipality": "Erie",
   "gps_code": "KERI",
   "iata_code": "ERI",
   "local_code": "ERI"
 },
 {
   "ident": "KEWR",
   "type": "large_airport",
   "name": "Newark Liberty International Airport",
   "coordinates": "40.69250107, -74.16870117",
   "elevation_ft": 18,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NJ",
   "municipality": "Newark",
   "gps_code": "KEWR",
   "iata_code": "EWR",
   "local_code": "EWR"
 },
 {
   "ident": "KFFO",
   "type": "large_airport",
   "name": "Wright-Patterson Air Force Base",
   "coordinates": "39.8260994, -84.0483017",
   "elevation_ft": 823,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OH",
   "municipality": "Dayton",
   "gps_code": "KFFO",
   "iata_code": "FFO",
   "local_code": "FFO"
 },
 {
   "ident": "KFLL",
   "type": "large_airport",
   "name": "Fort Lauderdale Hollywood International Airport",
   "coordinates": "26.07259941, -80.15270233",
   "elevation_ft": 9,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Fort Lauderdale",
   "gps_code": "KFLL",
   "iata_code": "FLL",
   "local_code": "FLL"
 },
 {
   "ident": "KFSM",
   "type": "large_airport",
   "name": "Fort Smith Regional Airport",
   "coordinates": "35.33660126, -94.36740112",
   "elevation_ft": 469,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AR",
   "municipality": "Fort Smith",
   "gps_code": "KFSM",
   "iata_code": "FSM",
   "local_code": "FSM"
 },
 {
   "ident": "KFTW",
   "type": "large_airport",
   "name": "Fort Worth Meacham International Airport",
   "coordinates": "32.81980133, -97.36239624",
   "elevation_ft": 710,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Fort Worth",
   "gps_code": "KFTW",
   "iata_code": "FTW",
   "local_code": "FTW"
 },
 {
   "ident": "KFWA",
   "type": "large_airport",
   "name": "Fort Wayne International Airport",
   "coordinates": "40.97850037, -85.19509888",
   "elevation_ft": 814,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IN",
   "municipality": "Fort Wayne",
   "gps_code": "KFWA",
   "iata_code": "FWA",
   "local_code": "FWA"
 },
 {
   "ident": "KGEG",
   "type": "large_airport",
   "name": "Spokane International Airport",
   "coordinates": "47.61989975, -117.5339966",
   "elevation_ft": 2376,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WA",
   "municipality": "Spokane",
   "gps_code": "KGEG",
   "iata_code": "GEG",
   "local_code": "GEG"
 },
 {
   "ident": "KGPT",
   "type": "large_airport",
   "name": "Gulfport Biloxi International Airport",
   "coordinates": "30.40730095, -89.07009888",
   "elevation_ft": 28,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MS",
   "municipality": "Gulfport",
   "gps_code": "KGPT",
   "iata_code": "GPT",
   "local_code": "GPT"
 },
 {
   "ident": "KGRB",
   "type": "large_airport",
   "name": "Austin Straubel International Airport",
   "coordinates": "44.48509979, -88.12960052",
   "elevation_ft": 695,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WI",
   "municipality": "Green Bay",
   "gps_code": "KGRB",
   "iata_code": "GRB",
   "local_code": "GRB"
 },
 {
   "ident": "KGSB",
   "type": "large_airport",
   "name": "Seymour Johnson Air Force Base",
   "coordinates": "35.33940125, -77.96060181",
   "elevation_ft": 109,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NC",
   "municipality": "Goldsboro",
   "gps_code": "KGSB",
   "iata_code": "GSB",
   "local_code": "GSB"
 },
 {
   "ident": "KGSO",
   "type": "large_airport",
   "name": "Piedmont Triad International Airport",
   "coordinates": "36.09780121, -79.93730164",
   "elevation_ft": 925,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NC",
   "municipality": "Greensboro",
   "gps_code": "KGSO",
   "iata_code": "GSO",
   "local_code": "GSO"
 },
 {
   "ident": "KGSP",
   "type": "large_airport",
   "name": "Greenville Spartanburg International Airport",
   "coordinates": "34.89569855, -82.21890259",
   "elevation_ft": 964,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-SC",
   "municipality": "Greenville",
   "gps_code": "KGSP",
   "iata_code": "GSP",
   "local_code": "GSP"
 },
 {
   "ident": "KGUS",
   "type": "large_airport",
   "name": "Grissom Air Reserve Base",
   "coordinates": "40.64810181, -86.15209961",
   "elevation_ft": 812,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IN",
   "municipality": "Peru",
   "gps_code": "KGUS",
   "iata_code": "GUS",
   "local_code": "GUS"
 },
 {
   "ident": "KHIB",
   "type": "large_airport",
   "name": "Range Regional Airport",
   "coordinates": "47.38660049, -92.83899689",
   "elevation_ft": 1354,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MN",
   "municipality": "Hibbing",
   "gps_code": "KHIB",
   "iata_code": "HIB",
   "local_code": "HIB"
 },
 {
   "ident": "KHMN",
   "type": "large_airport",
   "name": "Holloman Air Force Base",
   "coordinates": "32.85250092, -106.1070023",
   "elevation_ft": 4093,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NM",
   "municipality": "Alamogordo",
   "gps_code": "KHMN",
   "iata_code": "HMN",
   "local_code": "HMN"
 },
 {
   "ident": "KHOU",
   "type": "large_airport",
   "name": "William P Hobby Airport",
   "coordinates": "29.64539909, -95.27890015",
   "elevation_ft": 46,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Houston",
   "gps_code": "KHOU",
   "iata_code": "HOU",
   "local_code": "HOU"
 },
 {
   "ident": "KHSV",
   "type": "large_airport",
   "name": "Huntsville International Carl T Jones Field",
   "coordinates": "34.6371994, -86.77510071",
   "elevation_ft": 629,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AL",
   "municipality": "Huntsville",
   "gps_code": "KHSV",
   "iata_code": "HSV",
   "local_code": "HSV"
 },
 {
   "ident": "KHTS",
   "type": "large_airport",
   "name": "Tri-State/Milton J. Ferguson Field",
   "coordinates": "38.36669922, -82.55799866",
   "elevation_ft": 828,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WV",
   "municipality": "Huntington",
   "gps_code": "KHTS",
   "iata_code": "HTS",
   "local_code": "HTS"
 },
 {
   "ident": "KIAD",
   "type": "large_airport",
   "name": "Washington Dulles International Airport",
   "coordinates": "38.94449997, -77.45580292",
   "elevation_ft": 312,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-DC",
   "municipality": "Washington",
   "gps_code": "KIAD",
   "iata_code": "IAD",
   "local_code": "IAD"
 },
 {
   "ident": "KIAH",
   "type": "large_airport",
   "name": "George Bush Intercontinental Houston Airport",
   "coordinates": "29.9843998, -95.34140015",
   "elevation_ft": 97,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Houston",
   "gps_code": "KIAH",
   "iata_code": "IAH",
   "local_code": "IAH"
 },
 {
   "ident": "KICT",
   "type": "large_airport",
   "name": "Wichita Mid Continent Airport",
   "coordinates": "37.64989853, -97.43309784",
   "elevation_ft": 1333,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-KS",
   "municipality": "Wichita",
   "gps_code": "KICT",
   "iata_code": "ICT",
   "local_code": "ICT"
 },
 {
   "ident": "KIND",
   "type": "large_airport",
   "name": "Indianapolis International Airport",
   "coordinates": "39.71730042, -86.29440308",
   "elevation_ft": 797,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IN",
   "municipality": "Indianapolis",
   "gps_code": "KIND",
   "iata_code": "IND",
   "local_code": "IND"
 },
 {
   "ident": "KJAN",
   "type": "large_airport",
   "name": "Jackson-Medgar Wiley Evers International Airport",
   "coordinates": "32.31119919, -90.07589722",
   "elevation_ft": 346,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MS",
   "municipality": "Jackson",
   "gps_code": "KJAN",
   "iata_code": "JAN",
   "local_code": "JAN"
 },
 {
   "ident": "KJAX",
   "type": "large_airport",
   "name": "Jacksonville International Airport",
   "coordinates": "30.49410057, -81.68789673",
   "elevation_ft": 30,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Jacksonville",
   "gps_code": "KJAX",
   "iata_code": "JAX",
   "local_code": "JAX"
 },
 {
   "ident": "KJFK",
   "type": "large_airport",
   "name": "John F Kennedy International Airport",
   "coordinates": "40.63980103, -73.77890015",
   "elevation_ft": 13,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NY",
   "municipality": "New York",
   "gps_code": "KJFK",
   "iata_code": "JFK",
   "local_code": "JFK"
 },
 {
   "ident": "KJLN",
   "type": "large_airport",
   "name": "Joplin Regional Airport",
   "coordinates": "37.15179825, -94.49829865",
   "elevation_ft": 981,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MO",
   "municipality": "Joplin",
   "gps_code": "KJLN",
   "iata_code": "JLN",
   "local_code": "JLN"
 },
 {
   "ident": "KLAS",
   "type": "large_airport",
   "name": "McCarran International Airport",
   "coordinates": "36.08010101, -115.1520004",
   "elevation_ft": 2181,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NV",
   "municipality": "Las Vegas",
   "gps_code": "KLAS",
   "iata_code": "LAS",
   "local_code": "LAS"
 },
 {
   "ident": "KLAX",
   "type": "large_airport",
   "name": "Los Angeles International Airport",
   "coordinates": "33.94250107, -118.4079971",
   "elevation_ft": 125,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Los Angeles",
   "gps_code": "KLAX",
   "iata_code": "LAX",
   "local_code": "LAX"
 },
 {
   "ident": "KLBB",
   "type": "large_airport",
   "name": "Lubbock Preston Smith International Airport",
   "coordinates": "33.66360092, -101.822998",
   "elevation_ft": 3282,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Lubbock",
   "gps_code": "KLBB",
   "iata_code": "LBB",
   "local_code": "LBB"
 },
 {
   "ident": "KLCK",
   "type": "large_airport",
   "name": "Rickenbacker International Airport",
   "coordinates": "39.81380081, -82.92780304",
   "elevation_ft": 744,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OH",
   "municipality": "Columbus",
   "gps_code": "KLCK",
   "iata_code": "LCK",
   "local_code": "LCK"
 },
 {
   "ident": "KLEX",
   "type": "large_airport",
   "name": "Blue Grass Airport",
   "coordinates": "38.03649902, -84.60590363",
   "elevation_ft": 979,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-KY",
   "municipality": "Lexington",
   "gps_code": "KLEX",
   "iata_code": "LEX",
   "local_code": "LEX"
 },
 {
   "ident": "KLFI",
   "type": "large_airport",
   "name": "Langley Air Force Base",
   "coordinates": "37.082901, -76.36049652",
   "elevation_ft": 11,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-VA",
   "municipality": "Hampton",
   "gps_code": "KLFI",
   "iata_code": "LFI",
   "local_code": "LFI"
 },
 {
   "ident": "KLFT",
   "type": "large_airport",
   "name": "Lafayette Regional Airport",
   "coordinates": "30.20529938, -91.98760223",
   "elevation_ft": 42,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-LA",
   "municipality": "Lafayette",
   "gps_code": "KLFT",
   "iata_code": "LFT",
   "local_code": "LFT"
 },
 {
   "ident": "KLGA",
   "type": "large_airport",
   "name": "La Guardia Airport",
   "coordinates": "40.77719879, -73.87259674",
   "elevation_ft": 21,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NY",
   "municipality": "New York",
   "gps_code": "KLGA",
   "iata_code": "LGA",
   "local_code": "LGA"
 },
 {
   "ident": "KLIT",
   "type": "large_airport",
   "name": "Bill & Hillary Clinton National Airport/Adams Field",
   "coordinates": "34.72940063, -92.22429657",
   "elevation_ft": 262,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AR",
   "municipality": "Little Rock",
   "gps_code": "KLIT",
   "iata_code": "LIT",
   "local_code": "LIT"
 },
 {
   "ident": "KLTS",
   "type": "large_airport",
   "name": "Altus Air Force Base",
   "coordinates": "34.667099, -99.26670074",
   "elevation_ft": 1382,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OK",
   "municipality": "Altus",
   "gps_code": "KLTS",
   "iata_code": "LTS",
   "local_code": "LTS"
 },
 {
   "ident": "KLUF",
   "type": "large_airport",
   "name": "Luke Air Force Base",
   "coordinates": "33.53499985, -112.3830032",
   "elevation_ft": 1085,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AZ",
   "municipality": "Glendale",
   "gps_code": "KLUF",
   "iata_code": "LUF",
   "local_code": "LUF"
 },
 {
   "ident": "KMBS",
   "type": "large_airport",
   "name": "MBS International Airport",
   "coordinates": "43.53290176, -84.07959747",
   "elevation_ft": 668,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MI",
   "municipality": "Saginaw",
   "gps_code": "KMBS",
   "iata_code": "MBS",
   "local_code": "MBS"
 },
 {
   "ident": "KMCF",
   "type": "large_airport",
   "name": "Mac Dill Air Force Base",
   "coordinates": "27.84930038, -82.52120209",
   "elevation_ft": 14,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Tampa",
   "gps_code": "KMCF",
   "iata_code": "",
   "local_code": "MCF"
 },
 {
   "ident": "KMCI",
   "type": "large_airport",
   "name": "Kansas City International Airport",
   "coordinates": "39.29759979, -94.71389771",
   "elevation_ft": 1026,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MO",
   "municipality": "Kansas City",
   "gps_code": "KMCI",
   "iata_code": "MCI",
   "local_code": "MCI"
 },
 {
   "ident": "KMCO",
   "type": "large_airport",
   "name": "Orlando International Airport",
   "coordinates": "28.42939949, -81.30899811",
   "elevation_ft": 96,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Orlando",
   "gps_code": "KMCO",
   "iata_code": "MCO",
   "local_code": "MCO"
 },
 {
   "ident": "KMDW",
   "type": "large_airport",
   "name": "Chicago Midway International Airport",
   "coordinates": "41.7859993, -87.75240326",
   "elevation_ft": 620,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Chicago",
   "gps_code": "KMDW",
   "iata_code": "MDW",
   "local_code": "MDW"
 },
 {
   "ident": "KMEM",
   "type": "large_airport",
   "name": "Memphis International Airport",
   "coordinates": "35.04240036, -89.97669983",
   "elevation_ft": 341,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TN",
   "municipality": "Memphis",
   "gps_code": "KMEM",
   "iata_code": "MEM",
   "local_code": "MEM"
 },
 {
   "ident": "KMGE",
   "type": "large_airport",
   "name": "Dobbins Air Reserve Base Airport",
   "coordinates": "33.91540146, -84.51629639",
   "elevation_ft": 1068,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-GA",
   "municipality": "Marietta",
   "gps_code": "KMGE",
   "iata_code": "",
   "local_code": "MGE"
 },
 {
   "ident": "KMGM",
   "type": "large_airport",
   "name": "Montgomery Regional (Dannelly Field) Airport",
   "coordinates": "32.30059814, -86.39399719",
   "elevation_ft": 221,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AL",
   "municipality": "Montgomery",
   "gps_code": "KMGM",
   "iata_code": "MGM",
   "local_code": "MGM"
 },
 {
   "ident": "KMHT",
   "type": "large_airport",
   "name": "Manchester Airport",
   "coordinates": "42.93259811, -71.43569946",
   "elevation_ft": 266,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NH",
   "municipality": "Manchester",
   "gps_code": "KMHT",
   "iata_code": "MHT",
   "local_code": "MHT"
 },
 {
   "ident": "KMIA",
   "type": "large_airport",
   "name": "Miami International Airport",
   "coordinates": "25.79319954, -80.29060364",
   "elevation_ft": 8,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Miami",
   "gps_code": "KMIA",
   "iata_code": "MIA",
   "local_code": "MIA"
 },
 {
   "ident": "KMKE",
   "type": "large_airport",
   "name": "General Mitchell International Airport",
   "coordinates": "42.94720078, -87.89659882",
   "elevation_ft": 723,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WI",
   "municipality": "Milwaukee",
   "gps_code": "KMKE",
   "iata_code": "MKE",
   "local_code": "MKE"
 },
 {
   "ident": "KMLI",
   "type": "large_airport",
   "name": "Quad City International Airport",
   "coordinates": "41.44850159, -90.50749969",
   "elevation_ft": 590,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Moline",
   "gps_code": "KMLI",
   "iata_code": "MLI",
   "local_code": "MLI"
 },
 {
   "ident": "KMLU",
   "type": "large_airport",
   "name": "Monroe Regional Airport",
   "coordinates": "32.51089859, -92.03769684",
   "elevation_ft": 79,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-LA",
   "municipality": "Monroe",
   "gps_code": "KMLU",
   "iata_code": "MLU",
   "local_code": "MLU"
 },
 {
   "ident": "KMOB",
   "type": "large_airport",
   "name": "Mobile Regional Airport",
   "coordinates": "30.69120026, -88.24279785",
   "elevation_ft": 219,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AL",
   "municipality": "Mobile",
   "gps_code": "KMOB",
   "iata_code": "MOB",
   "local_code": "MOB"
 },
 {
   "ident": "KMSN",
   "type": "large_airport",
   "name": "Dane County Regional Truax Field",
   "coordinates": "43.13990021, -89.33750153",
   "elevation_ft": 887,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WI",
   "municipality": "Madison",
   "gps_code": "KMSN",
   "iata_code": "MSN",
   "local_code": "MSN"
 },
 {
   "ident": "KMSP",
   "type": "large_airport",
   "name": "Minneapolis-St Paul International/Wold-Chamberlain Airport",
   "coordinates": "44.88199997, -93.22180176",
   "elevation_ft": 841,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MN",
   "municipality": "Minneapolis",
   "gps_code": "KMSP",
   "iata_code": "MSP",
   "local_code": "MSP"
 },
 {
   "ident": "KMSY",
   "type": "large_airport",
   "name": "Louis Armstrong New Orleans International Airport",
   "coordinates": "29.99340057, -90.25800323",
   "elevation_ft": 4,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-LA",
   "municipality": "New Orleans",
   "gps_code": "KMSY",
   "iata_code": "MSY",
   "local_code": "MSY"
 },
 {
   "ident": "KMUO",
   "type": "large_airport",
   "name": "Mountain Home Air Force Base",
   "coordinates": "43.04359818, -115.8720016",
   "elevation_ft": 2996,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-ID",
   "municipality": "Mountain Home",
   "gps_code": "KMUO",
   "iata_code": "",
   "local_code": "MUO"
 },
 {
   "ident": "KOAK",
   "type": "large_airport",
   "name": "Metropolitan Oakland International Airport",
   "coordinates": "37.72129822, -122.2210007",
   "elevation_ft": 9,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Oakland",
   "gps_code": "KOAK",
   "iata_code": "OAK",
   "local_code": "OAK"
 },
 {
   "ident": "KOKC",
   "type": "large_airport",
   "name": "Will Rogers World Airport",
   "coordinates": "35.39310074, -97.60070038",
   "elevation_ft": 1295,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OK",
   "municipality": "Oklahoma City",
   "gps_code": "KOKC",
   "iata_code": "OKC",
   "local_code": "OKC"
 },
 {
   "ident": "KONT",
   "type": "large_airport",
   "name": "Ontario International Airport",
   "coordinates": "34.05599976, -117.6009979",
   "elevation_ft": 944,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Ontario",
   "gps_code": "KONT",
   "iata_code": "ONT",
   "local_code": "ONT"
 },
 {
   "ident": "KORD",
   "type": "large_airport",
   "name": "Chicago O'Hare International Airport",
   "coordinates": "41.97859955, -87.90480042",
   "elevation_ft": 672,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Chicago",
   "gps_code": "KORD",
   "iata_code": "ORD",
   "local_code": "ORD"
 },
 {
   "ident": "KORF",
   "type": "large_airport",
   "name": "Norfolk International Airport",
   "coordinates": "36.89459991, -76.20120239",
   "elevation_ft": 26,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-VA",
   "municipality": "Norfolk",
   "gps_code": "KORF",
   "iata_code": "ORF",
   "local_code": "ORF"
 },
 {
   "ident": "KPAM",
   "type": "large_airport",
   "name": "Tyndall Air Force Base",
   "coordinates": "30.06959915, -85.57540131",
   "elevation_ft": 17,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Panama City",
   "gps_code": "KPAM",
   "iata_code": "PAM",
   "local_code": "PAM"
 },
 {
   "ident": "KPBI",
   "type": "large_airport",
   "name": "Palm Beach International Airport",
   "coordinates": "26.68320084, -80.09559631",
   "elevation_ft": 19,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "West Palm Beach",
   "gps_code": "KPBI",
   "iata_code": "PBI",
   "local_code": "PBI"
 },
 {
   "ident": "KPDX",
   "type": "large_airport",
   "name": "Portland International Airport",
   "coordinates": "45.58869934, -122.5979996",
   "elevation_ft": 31,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OR",
   "municipality": "Portland",
   "gps_code": "KPDX",
   "iata_code": "PDX",
   "local_code": "PDX"
 },
 {
   "ident": "KPHF",
   "type": "large_airport",
   "name": "Newport News Williamsburg International Airport",
   "coordinates": "37.13190079, -76.49299622",
   "elevation_ft": 42,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-VA",
   "municipality": "Newport News",
   "gps_code": "KPHF",
   "iata_code": "PHF",
   "local_code": "PHF"
 },
 {
   "ident": "KPHL",
   "type": "large_airport",
   "name": "Philadelphia International Airport",
   "coordinates": "39.87189865, -75.2410965",
   "elevation_ft": 36,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-PA",
   "municipality": "Philadelphia",
   "gps_code": "KPHL",
   "iata_code": "PHL",
   "local_code": "PHL"
 },
 {
   "ident": "KPHX",
   "type": "large_airport",
   "name": "Phoenix Sky Harbor International Airport",
   "coordinates": "33.43429947, -112.012001",
   "elevation_ft": 1135,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AZ",
   "municipality": "Phoenix",
   "gps_code": "KPHX",
   "iata_code": "PHX",
   "local_code": "PHX"
 },
 {
   "ident": "KPIA",
   "type": "large_airport",
   "name": "General Wayne A. Downing Peoria International Airport",
   "coordinates": "40.66419983, -89.69329834",
   "elevation_ft": 660,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Peoria",
   "gps_code": "KPIA",
   "iata_code": "PIA",
   "local_code": "PIA"
 },
 {
   "ident": "KPIT",
   "type": "large_airport",
   "name": "Pittsburgh International Airport",
   "coordinates": "40.49150085, -80.23290253",
   "elevation_ft": 1203,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-PA",
   "municipality": "Pittsburgh",
   "gps_code": "KPIT",
   "iata_code": "PIT",
   "local_code": "PIT"
 },
 {
   "ident": "KPWM",
   "type": "large_airport",
   "name": "Portland International Jetport Airport",
   "coordinates": "43.64619827, -70.30930328",
   "elevation_ft": 76,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-ME",
   "municipality": "Portland",
   "gps_code": "KPWM",
   "iata_code": "PWM",
   "local_code": "PWM"
 },
 {
   "ident": "KRDU",
   "type": "large_airport",
   "name": "Raleigh Durham International Airport",
   "coordinates": "35.87760162, -78.78749847",
   "elevation_ft": 435,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NC",
   "municipality": "Raleigh/Durham",
   "gps_code": "KRDU",
   "iata_code": "RDU",
   "local_code": "RDU"
 },
 {
   "ident": "KRFD",
   "type": "large_airport",
   "name": "Chicago Rockford International Airport",
   "coordinates": "42.19540024, -89.09719849",
   "elevation_ft": 742,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Chicago/Rockford",
   "gps_code": "KRFD",
   "iata_code": "RFD",
   "local_code": "RFD"
 },
 {
   "ident": "KRIC",
   "type": "large_airport",
   "name": "Richmond International Airport",
   "coordinates": "37.50519943, -77.31970215",
   "elevation_ft": 167,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-VA",
   "municipality": "Richmond",
   "gps_code": "KRIC",
   "iata_code": "RIC",
   "local_code": "RIC"
 },
 {
   "ident": "KRND",
   "type": "large_airport",
   "name": "Randolph Air Force Base",
   "coordinates": "29.52969933, -98.27890015",
   "elevation_ft": 761,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Universal City",
   "gps_code": "KRND",
   "iata_code": "",
   "local_code": "RND"
 },
 {
   "ident": "KRNO",
   "type": "large_airport",
   "name": "Reno Tahoe International Airport",
   "coordinates": "39.49909973, -119.7679977",
   "elevation_ft": 4415,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NV",
   "municipality": "Reno",
   "gps_code": "KRNO",
   "iata_code": "RNO",
   "local_code": "RNO"
 },
 {
   "ident": "KROA",
   "type": "large_airport",
   "name": "Roanoke���Blacksburg Regional Airport",
   "coordinates": "37.32550049, -79.97540283",
   "elevation_ft": 1175,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-VA",
   "municipality": "Roanoke",
   "gps_code": "KROA",
   "iata_code": "ROA",
   "local_code": "ROA"
 },
 {
   "ident": "KROC",
   "type": "large_airport",
   "name": "Greater Rochester International Airport",
   "coordinates": "43.1189003, -77.67240143",
   "elevation_ft": 559,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NY",
   "municipality": "Rochester",
   "gps_code": "KROC",
   "iata_code": "ROC",
   "local_code": "ROC"
 },
 {
   "ident": "KRST",
   "type": "large_airport",
   "name": "Rochester International Airport",
   "coordinates": "43.90829849, -92.5",
   "elevation_ft": 1317,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MN",
   "municipality": "Rochester",
   "gps_code": "KRST",
   "iata_code": "RST",
   "local_code": "RST"
 },
 {
   "ident": "KRSW",
   "type": "large_airport",
   "name": "Southwest Florida International Airport",
   "coordinates": "26.53619957, -81.75520325",
   "elevation_ft": 30,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Fort Myers",
   "gps_code": "KRSW",
   "iata_code": "RSW",
   "local_code": "RSW"
 },
 {
   "ident": "KSAN",
   "type": "large_airport",
   "name": "San Diego International Airport",
   "coordinates": "32.73360062, -117.1900024",
   "elevation_ft": 17,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "San Diego",
   "gps_code": "KSAN",
   "iata_code": "SAN",
   "local_code": "SAN"
 },
 {
   "ident": "KSAT",
   "type": "large_airport",
   "name": "San Antonio International Airport",
   "coordinates": "29.53370094, -98.46980286",
   "elevation_ft": 809,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "San Antonio",
   "gps_code": "KSAT",
   "iata_code": "SAT",
   "local_code": "SAT"
 },
 {
   "ident": "KSAV",
   "type": "large_airport",
   "name": "Savannah Hilton Head International Airport",
   "coordinates": "32.12760162, -81.20210266",
   "elevation_ft": 50,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-GA",
   "municipality": "Savannah",
   "gps_code": "KSAV",
   "iata_code": "SAV",
   "local_code": "SAV"
 },
 {
   "ident": "KSBN",
   "type": "large_airport",
   "name": "South Bend Regional Airport",
   "coordinates": "41.70869827, -86.31729889",
   "elevation_ft": 799,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IN",
   "municipality": "South Bend",
   "gps_code": "KSBN",
   "iata_code": "SBN",
   "local_code": "SBN"
 },
 {
   "ident": "KSDF",
   "type": "large_airport",
   "name": "Louisville International Standiford Field",
   "coordinates": "38.17440033, -85.73600006",
   "elevation_ft": 501,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-KY",
   "municipality": "Louisville",
   "gps_code": "KSDF",
   "iata_code": "SDF",
   "local_code": "SDF"
 },
 {
   "ident": "KSEA",
   "type": "large_airport",
   "name": "Seattle Tacoma International Airport",
   "coordinates": "47.44900131, -122.3089981",
   "elevation_ft": 433,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WA",
   "municipality": "Seattle",
   "gps_code": "KSEA",
   "iata_code": "SEA",
   "local_code": "SEA"
 },
 {
   "ident": "KSFB",
   "type": "large_airport",
   "name": "Orlando Sanford International Airport",
   "coordinates": "28.77759933, -81.23750305",
   "elevation_ft": 55,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Orlando",
   "gps_code": "KSFB",
   "iata_code": "SFB",
   "local_code": "SFB"
 },
 {
   "ident": "KSFO",
   "type": "large_airport",
   "name": "San Francisco International Airport",
   "coordinates": "37.61899948, -122.375",
   "elevation_ft": 13,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "San Francisco",
   "gps_code": "KSFO",
   "iata_code": "SFO",
   "local_code": "SFO"
 },
 {
   "ident": "KSGF",
   "type": "large_airport",
   "name": "Springfield Branson National Airport",
   "coordinates": "37.24570084, -93.38860321",
   "elevation_ft": 1268,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MO",
   "municipality": "Springfield",
   "gps_code": "KSGF",
   "iata_code": "SGF",
   "local_code": "SGF"
 },
 {
   "ident": "KSHV",
   "type": "large_airport",
   "name": "Shreveport Regional Airport",
   "coordinates": "32.44660187, -93.82559967",
   "elevation_ft": 258,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-LA",
   "municipality": "Shreveport",
   "gps_code": "KSHV",
   "iata_code": "SHV",
   "local_code": "SHV"
 },
 {
   "ident": "KSJC",
   "type": "large_airport",
   "name": "Norman Y. Mineta San Jose International Airport",
   "coordinates": "37.36259842, -121.9290009",
   "elevation_ft": 62,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "San Jose",
   "gps_code": "KSJC",
   "iata_code": "SJC",
   "local_code": "SJC"
 },
 {
   "ident": "KSKA",
   "type": "large_airport",
   "name": "Fairchild Air Force Base",
   "coordinates": "47.61510086, -117.6559982",
   "elevation_ft": 2461,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WA",
   "municipality": "Spokane",
   "gps_code": "KSKA",
   "iata_code": "SKA",
   "local_code": "SKA"
 },
 {
   "ident": "KSLC",
   "type": "large_airport",
   "name": "Salt Lake City International Airport",
   "coordinates": "40.78839874, -111.9779968",
   "elevation_ft": 4227,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-UT",
   "municipality": "Salt Lake City",
   "gps_code": "KSLC",
   "iata_code": "SLC",
   "local_code": "SLC"
 },
 {
   "ident": "KSMF",
   "type": "large_airport",
   "name": "Sacramento International Airport",
   "coordinates": "38.69540024, -121.5910034",
   "elevation_ft": 27,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Sacramento",
   "gps_code": "KSMF",
   "iata_code": "SMF",
   "local_code": "SMF"
 },
 {
   "ident": "KSNA",
   "type": "large_airport",
   "name": "John Wayne Airport-Orange County Airport",
   "coordinates": "33.67570114, -117.8679962",
   "elevation_ft": 56,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Santa Ana",
   "gps_code": "KSNA",
   "iata_code": "SNA",
   "local_code": "SNA"
 },
 {
   "ident": "KSPI",
   "type": "large_airport",
   "name": "Abraham Lincoln Capital Airport",
   "coordinates": "39.84410095, -89.67790222",
   "elevation_ft": 598,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IL",
   "municipality": "Springfield",
   "gps_code": "KSPI",
   "iata_code": "SPI",
   "local_code": "SPI"
 },
 {
   "ident": "KSPS",
   "type": "large_airport",
   "name": "Sheppard Air Force Base-Wichita Falls Municipal Airport",
   "coordinates": "33.98880005, -98.49189758",
   "elevation_ft": 1019,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TX",
   "municipality": "Wichita Falls",
   "gps_code": "KSPS",
   "iata_code": "SPS",
   "local_code": "SPS"
 },
 {
   "ident": "KSRQ",
   "type": "large_airport",
   "name": "Sarasota Bradenton International Airport",
   "coordinates": "27.39539909, -82.55439758",
   "elevation_ft": 30,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Sarasota/Bradenton",
   "gps_code": "KSRQ",
   "iata_code": "SRQ",
   "local_code": "SRQ"
 },
 {
   "ident": "KSSC",
   "type": "large_airport",
   "name": "Shaw Air Force Base",
   "coordinates": "33.97269821, -80.47059631",
   "elevation_ft": 241,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-SC",
   "municipality": "Sumter",
   "gps_code": "KSSC",
   "iata_code": "",
   "local_code": "SSC"
 },
 {
   "ident": "KSTL",
   "type": "large_airport",
   "name": "Lambert St Louis International Airport",
   "coordinates": "38.74869919, -90.37000275",
   "elevation_ft": 618,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MO",
   "municipality": "St Louis",
   "gps_code": "KSTL",
   "iata_code": "STL",
   "local_code": "STL"
 },
 {
   "ident": "KSUS",
   "type": "large_airport",
   "name": "Spirit of St Louis Airport",
   "coordinates": "38.66210175, -90.65200043",
   "elevation_ft": 463,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MO",
   "municipality": "St Louis",
   "gps_code": "KSUS",
   "iata_code": "",
   "local_code": "SUS"
 },
 {
   "ident": "KSUU",
   "type": "large_airport",
   "name": "Travis Air Force Base",
   "coordinates": "38.26269913, -121.927002",
   "elevation_ft": 62,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Fairfield",
   "gps_code": "KSUU",
   "iata_code": "",
   "local_code": "SUU"
 },
 {
   "ident": "KSUX",
   "type": "large_airport",
   "name": "Sioux Gateway Col. Bud Day Field",
   "coordinates": "42.40259933, -96.38439941",
   "elevation_ft": 1098,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-IA",
   "municipality": "Sioux City",
   "gps_code": "KSUX",
   "iata_code": "SUX",
   "local_code": "SUX"
 },
 {
   "ident": "KSYR",
   "type": "large_airport",
   "name": "Syracuse Hancock International Airport",
   "coordinates": "43.11119843, -76.10630035",
   "elevation_ft": 421,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-NY",
   "municipality": "Syracuse",
   "gps_code": "KSYR",
   "iata_code": "SYR",
   "local_code": "SYR"
 },
 {
   "ident": "KSZL",
   "type": "large_airport",
   "name": "Whiteman Air Force Base",
   "coordinates": "38.7303009, -93.54789734",
   "elevation_ft": 870,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-MO",
   "municipality": "Knob Noster",
   "gps_code": "KSZL",
   "iata_code": "",
   "local_code": "SZL"
 },
 {
   "ident": "KTCM",
   "type": "large_airport",
   "name": "McChord Air Force Base",
   "coordinates": "47.13769913, -122.4759979",
   "elevation_ft": 322,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-WA",
   "municipality": "Tacoma",
   "gps_code": "KTCM",
   "iata_code": "TCM",
   "local_code": "TCM"
 },
 {
   "ident": "KTIK",
   "type": "large_airport",
   "name": "Tinker Air Force Base",
   "coordinates": "35.41469955, -97.38659668",
   "elevation_ft": 1291,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OK",
   "municipality": "Oklahoma City",
   "gps_code": "KTIK",
   "iata_code": "",
   "local_code": "TIK"
 },
 {
   "ident": "KTLH",
   "type": "large_airport",
   "name": "Tallahassee Regional Airport",
   "coordinates": "30.39649963, -84.35030365",
   "elevation_ft": 81,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Tallahassee",
   "gps_code": "KTLH",
   "iata_code": "TLH",
   "local_code": "TLH"
 },
 {
   "ident": "KTOL",
   "type": "large_airport",
   "name": "Toledo Express Airport",
   "coordinates": "41.58679962, -83.80780029",
   "elevation_ft": 683,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OH",
   "municipality": "Toledo",
   "gps_code": "KTOL",
   "iata_code": "TOL",
   "local_code": "TOL"
 },
 {
   "ident": "KTPA",
   "type": "large_airport",
   "name": "Tampa International Airport",
   "coordinates": "27.97550011, -82.53320313",
   "elevation_ft": 26,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Tampa",
   "gps_code": "KTPA",
   "iata_code": "TPA",
   "local_code": "TPA"
 },
 {
   "ident": "KTRI",
   "type": "large_airport",
   "name": "Tri Cities Regional Tn Va Airport",
   "coordinates": "36.47520065, -82.40740204",
   "elevation_ft": 1519,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TN",
   "municipality": "Bristol/Johnson/Kingsport",
   "gps_code": "KTRI",
   "iata_code": "TRI",
   "local_code": "TRI"
 },
 {
   "ident": "KTUL",
   "type": "large_airport",
   "name": "Tulsa International Airport",
   "coordinates": "36.19839859, -95.88809967",
   "elevation_ft": 677,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-OK",
   "municipality": "Tulsa",
   "gps_code": "KTUL",
   "iata_code": "TUL",
   "local_code": "TUL"
 },
 {
   "ident": "KTUS",
   "type": "large_airport",
   "name": "Tucson International Airport",
   "coordinates": "32.11610031, -110.9410019",
   "elevation_ft": 2643,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AZ",
   "municipality": "Tucson",
   "gps_code": "KTUS",
   "iata_code": "TUS",
   "local_code": "TUS"
 },
 {
   "ident": "KTYS",
   "type": "large_airport",
   "name": "McGhee Tyson Airport",
   "coordinates": "35.81100082, -83.9940033",
   "elevation_ft": 981,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-TN",
   "municipality": "Knoxville",
   "gps_code": "KTYS",
   "iata_code": "TYS",
   "local_code": "TYS"
 },
 {
   "ident": "KVBG",
   "type": "large_airport",
   "name": "Vandenberg Air Force Base",
   "coordinates": "34.73730087, -120.5839996",
   "elevation_ft": 369,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-CA",
   "municipality": "Lompoc",
   "gps_code": "KVBG",
   "iata_code": "VBG",
   "local_code": "VBG"
 },
 {
   "ident": "KVPS",
   "type": "large_airport",
   "name": "Eglin Air Force Base",
   "coordinates": "30.48320007, -86.52539825",
   "elevation_ft": 87,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-FL",
   "municipality": "Valparaiso",
   "gps_code": "KVPS",
   "iata_code": "VPS",
   "local_code": "VPS"
 },
 {
   "ident": "KWRB",
   "type": "large_airport",
   "name": "Robins Air Force Base",
   "coordinates": "32.64009857, -83.59190369",
   "elevation_ft": 294,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-GA",
   "municipality": "Warner Robins",
   "gps_code": "KWRB",
   "iata_code": "WRB",
   "local_code": "WRB"
 },
 {
   "ident": "PAFA",
   "type": "large_airport",
   "name": "Fairbanks International Airport",
   "coordinates": "64.81510162, -147.8560028",
   "elevation_ft": 439,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AK",
   "municipality": "Fairbanks",
   "gps_code": "PAFA",
   "iata_code": "FAI",
   "local_code": "FAI"
 },
 {
   "ident": "PANC",
   "type": "large_airport",
   "name": "Ted Stevens Anchorage International Airport",
   "coordinates": "61.17440033, -149.9960022",
   "elevation_ft": 152,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-AK",
   "municipality": "Anchorage",
   "gps_code": "PANC",
   "iata_code": "ANC",
   "local_code": "ANC"
 },
 {
   "ident": "PHNL",
   "type": "large_airport",
   "name": "Honolulu International Airport",
   "coordinates": "21.31870079, -157.9219971",
   "elevation_ft": 13,
   "continent": "NA",
   "iso_country": "US",
   "iso_region": "US-HI",
   "municipality": "Honolulu",
   "gps_code": "PHNL",
   "iata_code": "HNL",
   "local_code": "HNL"
 }
]
